### PR TITLE
ColPrac badge

### PR DESCRIPTION
**Pull request by serenity4**
Addresses #7. Any other suggestions besides the current changes about ColPrac?

### CODE REVIEW

**Comment by ktchu** [comment]
Looks good. No additional suggestions from a source code perspective. Thanks!

**Comment by ktchu** [comment]
I see that the CI is failing. I believe that this is related to Issue #9 (deployment of package docs to GitHub Pages). I'll try to fix that in the couple of days so that we can unblock this PR.

**Comment by serenity4** [comment]
After merging the latest `main` and performed the config changes, the documentation build passes.

**Review by ktchu — APPROVED** [review]
Looks good!

**Pull request merged**
